# Generated by Django 3.0.2 on 2020-04-05 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=10)),
                ('lname', models.TextField(max_length=10)),
                ('uname', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=10)),
                ('email', models.TextField(max_length=20)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('order_id', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='total_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uid', models.TextField(max_length=34)),
                ('product_name', models.TextField(default='', max_length=15)),
                ('product_cat', models.TextField(default='', max_length=50)),
                ('product_subcat', models.CharField(default='', max_length=50)),
                ('product_img', models.ImageField(upload_to='media')),
                ('puroduct_pubdate', models.DateTimeField(default=datetime.datetime(2020, 4, 5, 3, 19, 53, 518844, tzinfo=utc))),
                ('product_desc', models.TextField(default='', max_length=150)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
