# Generated by Django 3.0.2 on 2020-04-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_product',
            name='puroduct_pubdate',
            field=models.DateTimeField(),
        ),
    ]
